apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: barmagly

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - elasticsearch.yaml
  - minio.yaml
  - prometheus-config.yaml
  - monitoring.yaml
  - network-policy.yaml
  - deployments/api.yaml
  - deployments/web.yaml
  - deployments/worker.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: barmagly
  app.kubernetes.io/managed-by: kustomize
