export enum AutomationTriggerType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_MENTION = 'NEW_MENTION',
  NEW_COMMENT = 'NEW_COMMENT',
  POST_PUBLISHED = 'POST_PUBLISHED',
  POST_FAILED = 'POST_FAILED',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  KEYWORD_DETECTED = 'KEYWORD_DETECTED',
  SENTIMENT_NEGATIVE = 'SENTIMENT_NEGATIVE',
  CONTACT_CREATED = 'CONTACT_CREATED',
  EMAIL_OPENED = 'EMAIL_OPENED',
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  SCHEDULED_TIME = 'SCHEDULED_TIME',
}

export enum AutomationActionType {
  SEND_REPLY = 'SEND_REPLY',
  ASSIGN_TO = 'ASSIGN_TO',
  ADD_TAG = 'ADD_TAG',
  REMOVE_TAG = 'REMOVE_TAG',
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  CREATE_CONTACT = 'CREATE_CONTACT',
  UPDATE_CONTACT = 'UPDATE_CONTACT',
  ADD_TO_LIST = 'ADD_TO_LIST',
  WEBHOOK_CALL = 'WEBHOOK_CALL',
  WAIT = 'WAIT',
  CONDITION = 'CONDITION',
}

export enum AutomationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT',
}
